# Generated by Django 3.1 on 2020-09-04 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('siape', models.CharField(help_text='Requer 7 digitos numéricos.', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]'), 'Digite um Siape válido!', 'invalid')], verbose_name='Siape')),
                ('cpf', models.CharField(help_text='Digite apenas 11 digitos numéricos.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]'), 'Digite um CPF válido!', 'invalid')], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]'), 'Digite um RG válido!', 'invalid')], verbose_name='RG')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Servidor(a)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo(a)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado hein')),
                ('last_sign_in_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='Último IP logado')),
                ('last_sign_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso em')),
                ('current_sign_in_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP logado atual')),
                ('current_sign_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Acesso atual')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ingresso em')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dept', verbose_name='Campus')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sex', verbose_name='Sexo')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
