# Generated by Django 3.1 on 2020-12-11 21:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201211_1640'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userjif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIFProfile',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='JIFUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dept')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userjif.jifprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='jif_profiles',
            field=models.ManyToManyField(blank=True, help_text='O perfil é um conjunto de permissões que o usuário pode estar associado', related_name='jifuser_set', related_query_name='jifuser', through='userjif.JIFUserProfile', to='userjif.JIFProfile', verbose_name='Perfis'),
        ),
    ]
