# Generated by Django 3.1 on 2021-04-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
