# Generated by Django 3.1 on 2020-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0002_jifprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profiles',
            field=models.ManyToManyField(blank=True, help_text='O perfil é um conjunto de permissões que o usuário pode estar associado', related_name='jifuser_set', related_query_name='jifuser', to='userjif.JIFProfile', verbose_name='Perfis'),
        ),
    ]
