# Generated by Django 3.1 on 2021-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jifprofile',
            name='code',
            field=models.CharField(default=None, max_length=3, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
