# Generated by Django 3.1 on 2020-12-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0003_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jifprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do perfil'),
        ),
    ]
