# Generated by Django 3.1 on 2021-01-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_functiontypecommittee'),
        ('userjif', '0003_auto_20201211_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionTypeCommitteeUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.committee')),
                ('function_type_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.functiontypecommittee')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userjif.jifuserprofile')),
            ],
            options={
                'verbose_name': 'Função de Comissão',
                'verbose_name_plural': 'Funções de Comissões',
            },
        ),
        migrations.AddField(
            model_name='jifuserprofile',
            name='function_committees',
            field=models.ManyToManyField(blank=True, help_text='Este campo serve para informar qual função em determinada comissão é exercida', related_name='function_type_committee', through='userjif.FunctionTypeCommitteeUserProfile', to='core.FunctionTypeCommittee', verbose_name='Função da Comissão'),
        ),
    ]
