# Generated by Django 3.1 on 2020-12-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201211_1640'),
        ('userjif', '0004_jifprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIFUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dept')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userjif.jifprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='profiles',
            field=models.ManyToManyField(blank=True, help_text='O perfil é um conjunto de permissões que o usuário pode estar associado', related_name='jifuser_set', related_query_name='jifuser', through='userjif.JIFUserProfile', to='userjif.JIFProfile', verbose_name='Perfis'),
        ),
    ]
