# Generated by Django 3.1 on 2021-01-15 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_functiontypecommittee'),
        ('userjif', '0004_auto_20210115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontypecommitteeuserprofile',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.committee', verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='functiontypecommitteeuserprofile',
            name='function_type_committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.functiontypecommittee', verbose_name='Função da Comissão'),
        ),
        migrations.AlterField(
            model_name='functiontypecommitteeuserprofile',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userjif.jifuserprofile', verbose_name='Perfil de Usuário'),
        ),
        migrations.AlterField(
            model_name='jifuserprofile',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dept', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='jifuserprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userjif.jifprofile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='jifuserprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
