# Generated by Django 3.1 on 2020-08-31 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jifb',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 10, 30, 47, 383578)),
        ),
        migrations.AddField(
            model_name='jifb',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 10, 30, 47, 383578)),
        ),
    ]
