# Generated by Django 3.1 on 2020-08-31 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200831_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifb',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 10, 32, 30, 349769), verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jifb',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 10, 32, 30, 349769), verbose_name='Início'),
        ),
    ]
