# Generated by Django 3.1 on 2020-09-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_championship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonato'},
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('unique', models.BooleanField(verbose_name='Grupo único do campeonato?')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.championship', verbose_name='JIF')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.championship', verbose_name='JIF')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='JIF')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
    ]
