# Generated by Django 3.1 on 2021-04-16 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0001_initial'),
        ('core', '0002_jifsteam_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameteam',
            name='jif_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.jifsteam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameteam',
            name='score',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameteam',
            name='score_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scoretype'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='updater_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userjif.jifuserprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='gameteam',
            unique_together={('game', 'jif_team')},
        ),
    ]
