# Generated by Django 3.1 on 2021-04-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210416_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='csteams', through='core.ChampionshipsTeam', to='core.JIFsTeam'),
        ),
        migrations.AlterField(
            model_name='championshipsteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifsteam'),
        ),
    ]
