# Generated by Django 3.1 on 2020-08-31 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200831_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('acronym', models.CharField(max_length=10, verbose_name='Abreviação')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='jifb',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviação'),
        ),
        migrations.AlterField(
            model_name='jifb',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 11, 15, 53, 803416), verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jifb',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 11, 15, 53, 803416), verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='jifb',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=9, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='prefix',
            field=models.CharField(max_length=3, verbose_name='Prefixo'),
        ),
    ]
