# Generated by Django 3.1 on 2021-04-23 16:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0002_user_image'),
        ('core', '0004_auto_20210416_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameteam',
            options={'verbose_name': 'Time em Jogo', 'verbose_name_plural': 'Times em Jogos'},
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Digite apenas 11 digitos numéricos.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]'), 'Digite um CPF válido!', 'invalid')], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]'), 'Digite um RG válido!', 'invalid')], verbose_name='RG')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('birth_date', models.DateTimeField(verbose_name='Criado')),
                ('health_care', models.CharField(blank=True, max_length=30, null=True, verbose_name='Plano de Saúde')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado')),
                ('sus_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='N° do SUS')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes')),
                ('medicine', models.TextField(blank=True, null=True, verbose_name='Medicamentos')),
                ('ativo', models.BooleanField(verbose_name='Atleta ativo?')),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bloodtype')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dept', verbose_name='Campus')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sex', verbose_name='Sexo')),
                ('updater_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userjif.jifuserprofile')),
            ],
            options={
                'verbose_name': 'Time do Campeonato',
                'verbose_name_plural': 'Times dos Campeonatos',
            },
        ),
    ]
