# Generated by Django 3.1 on 2021-04-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210423_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='ativo',
            new_name='active',
        ),
    ]
