# Generated by Django 3.1 on 2020-08-31 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200831_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Sexo')),
                ('acronym', models.CharField(blank=True, max_length=2, null=True, verbose_name='Abreviação')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
        migrations.AlterModelOptions(
            name='jifb',
            options={'verbose_name': 'JIFB', 'verbose_name_plural': 'JIFBs'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AlterField(
            model_name='jifb',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 11, 46, 1, 712312), verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jifb',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 11, 46, 1, 712312), verbose_name='Início'),
        ),
    ]
