# Generated by Django 3.1 on 2020-09-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modality_modalitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIFModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modality')),
            ],
            options={
                'verbose_name': 'Modalidade do JIF',
                'verbose_name_plural': 'Modalidades dos JIFS',
            },
        ),
        migrations.AddField(
            model_name='jif',
            name='modalities',
            field=models.ManyToManyField(related_name='jif', through='core.JIFModality', to='core.Modality'),
        ),
    ]
