# Generated by Django 3.1 on 2021-04-23 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0002_user_image'),
        ('core', '0007_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'verbose_name': 'Atleta', 'verbose_name_plural': 'Atletas'},
        ),
        migrations.AddField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='athlete',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.athlete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='jif_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.jifsteam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updater_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userjif.jifuserprofile'),
        ),
    ]
