# Generated by Django 3.1 on 2020-09-01 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200831_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifb',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 9, 45, 52, 571214), verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jifb',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 9, 45, 52, 571214), verbose_name='Início'),
        ),
        migrations.CreateModel(
            name='DeptsPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dept')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phone')),
            ],
            options={
                'verbose_name': 'Telefone do Campus',
                'verbose_name_plural': 'Telefones dos Campi',
            },
        ),
    ]
