# Generated by Django 3.1 on 2020-10-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200922_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIFModalityRestricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jif_modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifmodality')),
            ],
            options={
                'verbose_name': 'Restrição de Modalidade do JIF',
                'verbose_name_plural': 'Restrições de Modalidades dos JIFS',
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Restrição',
                'verbose_name_plural': 'Restrições',
            },
        ),
        migrations.CreateModel(
            name='JIFModalityRestricionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Campo opicional para atribuir algum valor', max_length=100, null=True, verbose_name='Valor para restrição')),
                ('jif_modality_restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifmodalityrestricion')),
            ],
            options={
                'verbose_name': 'Modalidade do JIF',
                'verbose_name_plural': 'Modalidades dos JIFS',
            },
        ),
        migrations.AddField(
            model_name='jifmodalityrestricion',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restriction'),
        ),
    ]
