# Generated by Django 3.1 on 2020-10-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201029_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JIFModalityRestricion',
            new_name='JIFModalityRestriction',
        ),
    ]
