# Generated by Django 3.1 on 2020-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200901_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifb',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jifb',
            name='date_init',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Início'),
        ),
    ]
