# Generated by Django 3.1 on 2021-04-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210423_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameteam',
            name='score_type',
        ),
        migrations.AddField(
            model_name='modalitytype',
            name='score_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scoretype'),
        ),
        migrations.AlterField(
            model_name='scoretype',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
    ]
