# Generated by Django 3.1 on 2020-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200901_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptsphone',
            name='phone',
        ),
        migrations.AddField(
            model_name='deptsphone',
            name='number',
            field=models.CharField(default='XXXXXXXXX', max_length=9, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='deptsphone',
            name='prefix',
            field=models.CharField(default='XX', max_length=3, verbose_name='Prefixo'),
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
