# Generated by Django 3.1 on 2020-10-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201029_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JIFModalityRestricionValue',
            new_name='JIFModalityRestrictionValue',
        ),
    ]
