# Generated by Django 3.1 on 2020-12-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201029_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jifmodalityrestrictionvalue',
            options={'verbose_name': 'Valor de Restrição para modalidade', 'verbose_name_plural': 'Valores de Restrições para modalidades'},
        ),
    ]
