# Generated by Django 3.1 on 2020-09-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200901_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptsphone',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dept', verbose_name='Campus'),
        ),
    ]
