# Generated by Django 3.1 on 2021-04-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210426_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='jif',
        ),
        migrations.AddField(
            model_name='championship',
            name='jif_modality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.jifmodality', verbose_name='JIFModality'),
            preserve_default=False,
        ),
    ]
