# Generated by Django 3.1 on 2021-01-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201211_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionTypeCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome da Função de Comissão')),
                ('code', models.CharField(max_length=3, verbose_name='Código da Função de Comissão')),
                ('description', models.TextField(verbose_name='Descrição da Função de  Comissão')),
            ],
            options={
                'verbose_name': 'Função de Comissão',
                'verbose_name_plural': 'Funções de Comissões',
            },
        ),
    ]
