# Generated by Django 3.1 on 2020-09-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200901_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('edition', models.CharField(max_length=30, verbose_name='Edição')),
                ('date_init', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Fim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
            options={
                'verbose_name': 'JIFB',
                'verbose_name_plural': 'JIFBs',
            },
        ),
        migrations.CreateModel(
            name='JIFsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('date_init', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Fim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.DeleteModel(
            name='JIFB',
        ),
    ]
