# Generated by Django 3.1 on 2020-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200901_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jif',
            options={'verbose_name': 'JIF', 'verbose_name_plural': 'JIFs'},
        ),
        migrations.AlterField(
            model_name='jifsevent',
            name='date_end',
            field=models.DateTimeField(auto_now=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jifsevent',
            name='date_init',
            field=models.DateTimeField(auto_now=True, verbose_name='Início'),
        ),
    ]
