# Generated by Django 3.1 on 2021-04-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210427_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='blood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bloodtype', verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='athletes', verbose_name='Foto'),
        ),
    ]
