# Generated by Django 3.1 on 2021-01-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_functiontypecommittee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Score',
                'verbose_name_plural': 'Tipos de Scores',
            },
        ),
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Estado de Time',
                'verbose_name_plural': 'Estados de Times',
            },
        ),
        migrations.AlterField(
            model_name='jif',
            name='modalities',
            field=models.ManyToManyField(related_name='modalities', through='core.JIFModality', to='core.Modality'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('titular_member_quantity', models.IntegerField(verbose_name='Número de Integrantes Titulares')),
                ('reserve_members_quantity', models.IntegerField(verbose_name='Número de Integrantes Reservas')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dept', verbose_name='Campus')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifmodality')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sex')),
                ('team_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teamstatus')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='JIFsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.AddField(
            model_name='jif',
            name='teams',
            field=models.ManyToManyField(related_name='teams', through='core.JIFsTeam', to='core.Team'),
        ),
    ]
