# Generated by Django 3.1 on 2021-01-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210121_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modality'),
        ),
    ]
