# Generated by Django 3.1 on 2020-09-01 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200901_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifsevent',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jifsevent',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Início'),
        ),
    ]
