# Generated by Django 3.1 on 2021-05-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0002_user_image'),
        ('core', '0014_auto_20210505_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.championship', verbose_name='Campeonato'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Atleta'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='jif_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifsteam', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updater_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userjif.jifuserprofile', verbose_name='Perfil de Atualização do Usuário'),
        ),
    ]
