# Generated by Django 3.1 on 2021-05-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210510_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoretype',
            options={'verbose_name': 'Tipo de Pontuação', 'verbose_name_plural': 'Tipos de Pontuações'},
        ),
        migrations.AlterField(
            model_name='championshipsteam',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.championship', verbose_name='Campeonato'),
        ),
        migrations.AlterField(
            model_name='championshipsteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifsteam', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.championship', verbose_name='Campeonato'),
        ),
        migrations.AlterField(
            model_name='game',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='gameteam',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='gameteam',
            name='jif_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifsteam', verbose_name='Time do JIF'),
        ),
        migrations.AlterField(
            model_name='gameteam',
            name='score',
            field=models.IntegerField(verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='jifmodality',
            name='jif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF'),
        ),
        migrations.AlterField(
            model_name='jifmodality',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modality', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='jifmodalityrestriction',
            name='jif_modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jifmodality', verbose_name='Modalidade do JIF'),
        ),
        migrations.AlterField(
            model_name='jifmodalityrestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restriction', verbose_name='Restrição'),
        ),
        migrations.AlterField(
            model_name='jifsteam',
            name='jif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF'),
        ),
        migrations.AlterField(
            model_name='jifsteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='jifsteam',
            name='team_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teamstatus', verbose_name='Situação do Time'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='modality_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modalitytype', verbose_name='Tipo de Modalidade'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sex', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='modalitytype',
            name='score_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scoretype', verbose_name='Tipo de Pontuação'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags', verbose_name='Bandeira'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modality', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sex', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teamstatus', verbose_name='Situação do Time'),
        ),
    ]
