# Generated by Django 3.1 on 2021-01-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210121_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jif',
            name='modalities',
            field=models.ManyToManyField(null=True, related_name='modalities', through='core.JIFModality', to='core.Modality'),
        ),
        migrations.AlterField(
            model_name='jif',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', through='core.JIFsTeam', to='core.Team'),
        ),
    ]
