# Generated by Django 3.1 on 2020-09-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200901_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome da Comissão')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
    ]
