# Generated by Django 3.1 on 2021-05-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210512_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalityGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviação')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Agrupamento de Modalidade',
                'verbose_name_plural': 'Agrupamentos de Modalidades',
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='registration',
            field=models.CharField(default=None, max_length=11, unique=True, verbose_name='Matrícula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modality',
            name='grouping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modalitygrouping', verbose_name='Agrupamento'),
        ),
    ]
