# Generated by Django 3.1 on 2021-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210121_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jif',
            name='modalities',
            field=models.ManyToManyField(blank=True, null=True, related_name='modalities', through='core.JIFModality', to='core.Modality'),
        ),
    ]
