# Generated by Django 3.1 on 2021-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210514_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitygrouping',
            name='acronym',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Abreviação'),
        ),
    ]
