# Generated by Django 3.1 on 2021-06-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210608_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JIFsEvent',
        ),
    ]
