# Generated by Django 3.1 on 2021-06-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0004_auto_20210610_1139'),
        ('core', '0019_delete_jifsevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='jif',
        ),
        migrations.DeleteModel(
            name='FunctionTypeCommittee',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
