# Generated by Django 3.1 on 2021-01-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210121_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jif',
            name='modalities',
            field=models.ManyToManyField(related_name='modalities', through='core.JIFModality', to='core.Modality'),
        ),
        migrations.AlterField(
            model_name='jif',
            name='teams',
            field=models.ManyToManyField(related_name='teams', through='core.JIFsTeam', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='jifmodality',
            name='jif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif'),
        ),
        migrations.AlterField(
            model_name='jifmodality',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modality'),
        ),
        migrations.AlterField(
            model_name='jifsteam',
            name='jif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif'),
        ),
        migrations.AlterField(
            model_name='jifsteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
