# Generated by Django 3.1 on 2021-06-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0005_auto_20210610_1813'),
        ('dept', '0001_initial'),
        ('core', '0020_auto_20210610_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptsphone',
            name='dept',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.dept', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='team',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.dept', verbose_name='Campus'),
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.DeleteModel(
            name='DeptsPhone',
        ),
    ]
