# Generated by Django 3.1 on 2021-06-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userjif', '0006_auto_20210611_0938'),
        ('sex', '0001_initial'),
        ('core', '0021_auto_20210610_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sex.sex', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sex.sex', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sex.sex', verbose_name='Sexo'),
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
