# Generated by Django 3.1 on 2021-06-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210611_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jifmodality',
            name='jif',
        ),
        migrations.RemoveField(
            model_name='jifmodality',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='modality',
            name='grouping',
        ),
        migrations.RemoveField(
            model_name='modality',
            name='modality_type',
        ),
        migrations.RemoveField(
            model_name='modality',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='modalitytype',
            name='score_type',
        ),
    ]
