# Generated by Django 3.1 on 2021-06-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210611_1219'),
        ('modality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='jif_modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.jifmodality', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='jif',
            name='modalities',
            field=models.ManyToManyField(blank=True, related_name='modalities', through='modality.JIFModality', to='modality.Modality'),
        ),
        migrations.AlterField(
            model_name='jifmodalityrestriction',
            name='jif_modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.jifmodality', verbose_name='Modalidade do JIF'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.modality', verbose_name='Modalidade'),
        ),
        migrations.DeleteModel(
            name='JIFModality',
        ),
        migrations.DeleteModel(
            name='Modality',
        ),
        migrations.DeleteModel(
            name='ModalityGrouping',
        ),
        migrations.DeleteModel(
            name='ModalityType',
        ),
        migrations.DeleteModel(
            name='ScoreType',
        ),
    ]
