# Generated by Django 3.1 on 2021-06-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210611_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jifmodalityrestrictionvalue',
            name='jif_modality_restriction',
        ),
        migrations.DeleteModel(
            name='JIFModalityRestriction',
        ),
        migrations.DeleteModel(
            name='JIFModalityRestrictionValue',
        ),
        migrations.DeleteModel(
            name='Restriction',
        ),
    ]
