# Generated by Django 3.1 on 2021-06-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210611_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='jif_modality',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='championshipsteam',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='championshipsteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='gameteam',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gameteam',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameteam',
            name='jif_team',
        ),
        migrations.RemoveField(
            model_name='gameteam',
            name='updater_profile',
        ),
        migrations.RemoveField(
            model_name='group',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='jifsteam',
            name='jif',
        ),
        migrations.RemoveField(
            model_name='jifsteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='jifsteam',
            name='team_status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='team',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_status',
        ),
    ]
