# Generated by Django 3.1 on 2021-06-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('core', '0027_auto_20210611_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jif',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', through='team.JIFsTeam', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='jif_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.jifsteam', verbose_name='Time'),
        ),
        migrations.DeleteModel(
            name='Championship',
        ),
        migrations.DeleteModel(
            name='ChampionshipsTeam',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameTeam',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='JIFsTeam',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamStatus',
        ),
    ]
