# Generated by Django 3.1 on 2021-06-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_delete_jifsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionTypeCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome da Função de Comissão')),
                ('code', models.CharField(max_length=3, verbose_name='Código da Função de Comissão')),
                ('description', models.TextField(verbose_name='Descrição da Função de  Comissão')),
            ],
            options={
                'verbose_name': 'Função de Comissão',
                'verbose_name_plural': 'Funções de Comissões',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome da Comissão')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
    ]
