# Generated by Django 3.1 on 2021-06-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviação')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.CreateModel(
            name='DeptsPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='XX', max_length=3, verbose_name='Prefixo')),
                ('number', models.CharField(default='XXXXXXXXX', max_length=9, verbose_name='Número')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.dept', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Telefone do Campus',
                'verbose_name_plural': 'Telefones dos Campi',
            },
        ),
    ]
