# Generated by Django 3.1 on 2021-06-11 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_auto_20210611_1733'),
        ('modality', '0001_initial'),
        ('sex', '0001_initial'),
        ('championship', '0001_initial'),
        ('dept', '0001_initial'),
        ('userjif', '0006_auto_20210611_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Situação de Time',
                'verbose_name_plural': 'Situações de Times',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags', verbose_name='Bandeira')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('titular_member_quantity', models.IntegerField(verbose_name='Número de Integrantes Titulares')),
                ('reserve_members_quantity', models.IntegerField(verbose_name='Número de Integrantes Reservas')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.dept', verbose_name='Campus')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.modality', verbose_name='Modalidade')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sex.sex', verbose_name='Sexo')),
                ('team_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teamstatus', verbose_name='Situação do Time')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='JIFsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Time')),
                ('team_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teamstatus', verbose_name='Situação do Time')),
            ],
            options={
                'verbose_name': 'Time de JIF',
                'verbose_name_plural': 'Times de JIFs',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.championship', verbose_name='Campeonato')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.jifsteam', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Time do Campeonato',
                'verbose_name_plural': 'Times dos Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Pontuação')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.game', verbose_name='Jogo')),
                ('jif_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.jifsteam', verbose_name='Time do JIF')),
                ('updater_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userjif.jifuserprofile')),
            ],
            options={
                'verbose_name': 'Time em Jogo',
                'verbose_name_plural': 'Times em Jogos',
                'unique_together': {('game', 'jif_team')},
            },
        ),
    ]
