# Generated by Django 3.1 on 2021-06-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='csteams', through='team.ChampionshipsTeam', to='team.JIFsTeam', verbose_name='Times'),
        ),
    ]
