# Generated by Django 3.1 on 2021-06-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_auto_20210611_1219'),
        ('sex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalityGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('acronym', models.CharField(blank=True, max_length=1, null=True, verbose_name='Abreviação')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Agrupamento de Modalidade',
                'verbose_name_plural': 'Agrupamentos de Modalidades',
            },
        ),
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Pontuação',
                'verbose_name_plural': 'Tipos de Pontuações',
            },
        ),
        migrations.CreateModel(
            name='ModalityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('score_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modality.scoretype', verbose_name='Tipo de Pontuação')),
            ],
            options={
                'verbose_name': 'Tipo de Modalidade',
                'verbose_name_plural': 'Tipos de Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('grouping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modality.modalitygrouping', verbose_name='Agrupamento')),
                ('modality_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modality.modalitytype', verbose_name='Tipo de Modalidade')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sex.sex', verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='JIFModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.modality', verbose_name='Modalidade')),
            ],
            options={
                'verbose_name': 'Modalidade do JIF',
                'verbose_name_plural': 'Modalidades dos JIFS',
            },
        ),
    ]
