# Generated by Django 3.1 on 2021-06-10 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_delete_jifsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIFsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('date_init', models.DateTimeField(default=datetime.datetime.now, verbose_name='Início')),
                ('date_end', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('jif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jif', verbose_name='JIF')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
