# Generated by Django 3.1 on 2021-06-11 21:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userjif', '0006_auto_20210611_0938'),
        ('team', '0001_initial'),
        ('dept', '0001_initial'),
        ('sex', '0001_initial'),
        ('blood_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('cpf', models.CharField(help_text='Digite apenas 11 digitos numéricos.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]'), 'Digite um CPF válido!', 'invalid')], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]'), 'Digite um RG válido!', 'invalid')], verbose_name='RG')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('registration', models.CharField(max_length=11, unique=True, verbose_name='Matrícula')),
                ('birth_date', models.DateField(verbose_name='Data de Aniversário')),
                ('health_care', models.CharField(blank=True, max_length=30, null=True, verbose_name='Plano de Saúde')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado')),
                ('sus_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='N° do SUS')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes', verbose_name='Foto')),
                ('medicine', models.TextField(blank=True, null=True, verbose_name='Medicamentos')),
                ('active', models.BooleanField(verbose_name='Atleta ativo?')),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_type.bloodtype', verbose_name='Tipo Sanguíneo')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.dept', verbose_name='Campus')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sex.sex', verbose_name='Sexo')),
                ('updater_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userjif.jifuserprofile')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Atualizado')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.athlete', verbose_name='Atleta')),
                ('jif_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.jifsteam', verbose_name='Time')),
                ('updater_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userjif.jifuserprofile', verbose_name='Perfil de Atualização do Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
