# Generated by Django 3.1 on 2021-06-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIFModalityRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jif_modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modality.jifmodality', verbose_name='Modalidade do JIF')),
            ],
            options={
                'verbose_name': 'Restrição de Modalidade do JIF',
                'verbose_name_plural': 'Restrições de Modalidades dos JIFS',
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Restrição',
                'verbose_name_plural': 'Restrições',
            },
        ),
        migrations.CreateModel(
            name='JIFModalityRestrictionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Campo opicional para atribuir algum valor', max_length=100, null=True, verbose_name='Valor para restrição')),
                ('jif_modality_restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restriction.jifmodalityrestriction')),
            ],
            options={
                'verbose_name': 'Valor de Restrição para modalidade',
                'verbose_name_plural': 'Valores de Restrições para modalidades',
            },
        ),
        migrations.AddField(
            model_name='jifmodalityrestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restriction.restriction', verbose_name='Restrição'),
        ),
    ]
